/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Menus;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;
import Views.Mantenimientos.GenerarSuministrosView;
import Views.Mantenimientos.InventarioSuministroView;
import Views.Mantenimientos.MantenimientoProductosCompuestosView;
import Views.Mantenimientos.MantenimientoSuministrosView;

/**
 *
 * @author danie
 */
public class MenuSuministrosView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public MenuSuministrosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackbround = new javax.swing.JPanel();
        pnlUsuario = new javax.swing.JPanel();
        lblIconoUsuarioActual = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        lblMensajeBienvenida = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JPanel();
        lblIconoRegresar = new javax.swing.JLabel();
        lblRegresar = new javax.swing.JLabel();
        btnMantenimientoProductosCompuestos = new javax.swing.JPanel();
        lblIconoMantenimientoProductosCompuestos = new javax.swing.JLabel();
        lblMantenimientoProductosCompuestos2 = new javax.swing.JLabel();
        lblMantenimientoProductosCompuestos1 = new javax.swing.JLabel();
        btnGenerarSuministros = new javax.swing.JPanel();
        lblIconoGenerarSuministros = new javax.swing.JLabel();
        lblGenerarSuministros2 = new javax.swing.JLabel();
        lblGenerarSuministros1 = new javax.swing.JLabel();
        btnInventarioSuministros = new javax.swing.JPanel();
        lblIconoInventarioSuministros = new javax.swing.JLabel();
        lblInventarioSuministros2 = new javax.swing.JLabel();
        lblInventarioSuministros1 = new javax.swing.JLabel();
        btnMantenimientoInventarioSuministros = new javax.swing.JPanel();
        lblIconoMantenimientoInventarioSuministros = new javax.swing.JLabel();
        lblMantenimientoInventarioSuministros2 = new javax.swing.JLabel();
        lblMantenimientoInventarioSuministros1 = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblModulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBackbround.setBackground(new java.awt.Color(0, 49, 110));
        pnlBackbround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUsuario.setBackground(new java.awt.Color(0, 49, 110));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUsuarioActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_user_32px.png"))); // NOI18N
        pnlUsuario.add(lblIconoUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblUsuarioActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioActual.setForeground(new java.awt.Color(242, 242, 242));
        lblUsuarioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioActual.setText("Dra. Lourdes");
        pnlUsuario.add(lblUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 28));

        lblMensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensajeBienvenida.setForeground(new java.awt.Color(242, 242, 242));
        lblMensajeBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeBienvenida.setText("Bienvenido(a)");
        pnlUsuario.add(lblMensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 28));

        pnlBackbround.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        pnlMenu.setBackground(new java.awt.Color(0, 49, 110));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(45, 83, 150));
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        lblIconoRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_go_back_32px.png"))); // NOI18N

        lblRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(242, 242, 242));
        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegresar.setText("Regresar");

        javax.swing.GroupLayout btnRegresarLayout = new javax.swing.GroupLayout(btnRegresar);
        btnRegresar.setLayout(btnRegresarLayout);
        btnRegresarLayout.setHorizontalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnRegresarLayout.setVerticalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenu.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, 30));

        btnMantenimientoProductosCompuestos.setBackground(new java.awt.Color(45, 83, 150));
        btnMantenimientoProductosCompuestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnMantenimientoProductosCompuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimientoProductosCompuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantenimientoProductosCompuestosMouseClicked(evt);
            }
        });
        btnMantenimientoProductosCompuestos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMantenimientoProductosCompuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_product_32px.png"))); // NOI18N
        btnMantenimientoProductosCompuestos.add(lblIconoMantenimientoProductosCompuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        lblMantenimientoProductosCompuestos2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoProductosCompuestos2.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoProductosCompuestos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoProductosCompuestos2.setText("Productos Compuestos");
        btnMantenimientoProductosCompuestos.add(lblMantenimientoProductosCompuestos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 20));

        lblMantenimientoProductosCompuestos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoProductosCompuestos1.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoProductosCompuestos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoProductosCompuestos1.setText("Mantenimiento");
        btnMantenimientoProductosCompuestos.add(lblMantenimientoProductosCompuestos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 20));

        pnlMenu.add(btnMantenimientoProductosCompuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 180, 110));

        btnGenerarSuministros.setBackground(new java.awt.Color(45, 83, 150));
        btnGenerarSuministros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnGenerarSuministros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarSuministros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarSuministrosMouseClicked(evt);
            }
        });
        btnGenerarSuministros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoGenerarSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_barcode_32px.png"))); // NOI18N
        btnGenerarSuministros.add(lblIconoGenerarSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblGenerarSuministros2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGenerarSuministros2.setForeground(new java.awt.Color(242, 242, 242));
        lblGenerarSuministros2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenerarSuministros2.setText("Suministros");
        btnGenerarSuministros.add(lblGenerarSuministros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 80, 80, 20));

        lblGenerarSuministros1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGenerarSuministros1.setForeground(new java.awt.Color(242, 242, 242));
        lblGenerarSuministros1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenerarSuministros1.setText("Generar");
        btnGenerarSuministros.add(lblGenerarSuministros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        pnlMenu.add(btnGenerarSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, 110));

        btnInventarioSuministros.setBackground(new java.awt.Color(45, 83, 150));
        btnInventarioSuministros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnInventarioSuministros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventarioSuministros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventarioSuministrosMouseClicked(evt);
            }
        });
        btnInventarioSuministros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoInventarioSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_view_details_32px.png"))); // NOI18N
        btnInventarioSuministros.add(lblIconoInventarioSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 20, -1, -1));

        lblInventarioSuministros2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInventarioSuministros2.setForeground(new java.awt.Color(242, 242, 242));
        lblInventarioSuministros2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventarioSuministros2.setText("Suministros");
        btnInventarioSuministros.add(lblInventarioSuministros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 150, 20));

        lblInventarioSuministros1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInventarioSuministros1.setForeground(new java.awt.Color(242, 242, 242));
        lblInventarioSuministros1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventarioSuministros1.setText("Inventario");
        btnInventarioSuministros.add(lblInventarioSuministros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 20));

        pnlMenu.add(btnInventarioSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 160, 110));

        btnMantenimientoInventarioSuministros.setBackground(new java.awt.Color(45, 83, 150));
        btnMantenimientoInventarioSuministros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnMantenimientoInventarioSuministros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimientoInventarioSuministros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantenimientoInventarioSuministrosMouseClicked(evt);
            }
        });
        btnMantenimientoInventarioSuministros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMantenimientoInventarioSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_box_32px.png"))); // NOI18N
        btnMantenimientoInventarioSuministros.add(lblIconoMantenimientoInventarioSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 20, -1, -1));

        lblMantenimientoInventarioSuministros2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoInventarioSuministros2.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoInventarioSuministros2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoInventarioSuministros2.setText("Inventario Suministros");
        btnMantenimientoInventarioSuministros.add(lblMantenimientoInventarioSuministros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 20));

        lblMantenimientoInventarioSuministros1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoInventarioSuministros1.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoInventarioSuministros1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoInventarioSuministros1.setText("Mantenimiento");
        btnMantenimientoInventarioSuministros.add(lblMantenimientoInventarioSuministros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        pnlMenu.add(btnMantenimientoInventarioSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, 110));

        pnlBackbround.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 920, 420));

        pnlTitulo.setBackground(new java.awt.Color(0, 49, 110));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(242, 242, 242));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Inventario Hospital Odontológico");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        lblModulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblModulo.setForeground(new java.awt.Color(242, 242, 242));
        lblModulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModulo.setText("Menú Suministros");
        pnlTitulo.add(lblModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/Isotipo.HospitalOdontológico.UNICAH (4).png"))); // NOI18N
        pnlTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 90));

        pnlBackbround.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 710, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackbround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackbround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        MenuInicioView menuInicioView = new MenuInicioView();
        menuInicioView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnMantenimientoInventarioSuministrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoInventarioSuministrosMouseClicked
        MantenimientoSuministrosView mantenimientoSuministrosView = new MantenimientoSuministrosView();
        mantenimientoSuministrosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoInventarioSuministrosMouseClicked

    private void btnMantenimientoProductosCompuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoProductosCompuestosMouseClicked
        MantenimientoProductosCompuestosView mantenimientoProductosCompuestosView = new MantenimientoProductosCompuestosView();
        mantenimientoProductosCompuestosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoProductosCompuestosMouseClicked

    private void btnGenerarSuministrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarSuministrosMouseClicked
        GenerarSuministrosView generarSuministrosView = new GenerarSuministrosView();
        generarSuministrosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenerarSuministrosMouseClicked

    private void btnInventarioSuministrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioSuministrosMouseClicked
        InventarioSuministroView inventarioSuministroView = new InventarioSuministroView();
        inventarioSuministroView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInventarioSuministrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSuministrosView().setVisible(true);
            }
        });
    }
    
    private void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(45,83,150));
    }
    
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(0,49,110));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnGenerarSuministros;
    private javax.swing.JPanel btnInventarioSuministros;
    private javax.swing.JPanel btnMantenimientoInventarioSuministros;
    private javax.swing.JPanel btnMantenimientoProductosCompuestos;
    private javax.swing.JPanel btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGenerarSuministros1;
    private javax.swing.JLabel lblGenerarSuministros2;
    private javax.swing.JLabel lblIconoGenerarSuministros;
    private javax.swing.JLabel lblIconoInventarioSuministros;
    private javax.swing.JLabel lblIconoMantenimientoInventarioSuministros;
    private javax.swing.JLabel lblIconoMantenimientoProductosCompuestos;
    private javax.swing.JLabel lblIconoRegresar;
    private javax.swing.JLabel lblIconoUsuarioActual;
    private javax.swing.JLabel lblInventarioSuministros1;
    private javax.swing.JLabel lblInventarioSuministros2;
    private javax.swing.JLabel lblMantenimientoInventarioSuministros1;
    private javax.swing.JLabel lblMantenimientoInventarioSuministros2;
    private javax.swing.JLabel lblMantenimientoProductosCompuestos1;
    private javax.swing.JLabel lblMantenimientoProductosCompuestos2;
    private javax.swing.JLabel lblMensajeBienvenida;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JPanel pnlBackbround;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlUsuario;
    // End of variables declaration//GEN-END:variables
}
