/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Menus;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;
import Views.Mantenimientos.InventarioBodegaView;
import Views.Mantenimientos.MantenimientoCatalogoBodegaView;

/**
 *
 * @author danie
 */
public class MenuBodegaView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public MenuBodegaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackbround = new javax.swing.JPanel();
        pnlUsuario = new javax.swing.JPanel();
        lblIconoUsuarioAcual = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        lblMensajeBienvenida = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnMantenimientoCatalogoProductos1 = new javax.swing.JPanel();
        lblIconoMantenimientoCatalogoProductos1 = new javax.swing.JLabel();
        lblMantenimientoCatalogoProductos3 = new javax.swing.JLabel();
        lblMantenimientoCatalogoProductos4 = new javax.swing.JLabel();
        btnInventarioBodega = new javax.swing.JPanel();
        lblIconoInventarioBodega = new javax.swing.JLabel();
        lblInventarioBodega2 = new javax.swing.JLabel();
        lblInventarioBodega1 = new javax.swing.JLabel();
        btnMantenimientoCatalogoBodega = new javax.swing.JPanel();
        lblIconoMantenimientoCatalogoBodega = new javax.swing.JLabel();
        lblMantenimientoCatalogoBodega2 = new javax.swing.JLabel();
        lblMantenimientoCatalogoBodega1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JPanel();
        lblIconoRegresar = new javax.swing.JLabel();
        lblRegresar = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblModulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBackbround.setBackground(new java.awt.Color(0, 49, 110));
        pnlBackbround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUsuario.setBackground(new java.awt.Color(0, 49, 110));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUsuarioAcual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_user_32px.png"))); // NOI18N
        pnlUsuario.add(lblIconoUsuarioAcual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblUsuarioActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioActual.setForeground(new java.awt.Color(242, 242, 242));
        lblUsuarioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioActual.setText("Dra. Lourdes");
        pnlUsuario.add(lblUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 28));

        lblMensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensajeBienvenida.setForeground(new java.awt.Color(242, 242, 242));
        lblMensajeBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeBienvenida.setText("Bienvenido(a)");
        pnlUsuario.add(lblMensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 28));

        pnlBackbround.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        pnlMenu.setBackground(new java.awt.Color(0, 49, 110));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMantenimientoCatalogoProductos1.setBackground(new java.awt.Color(45, 83, 150));
        btnMantenimientoCatalogoProductos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnMantenimientoCatalogoProductos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimientoCatalogoProductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantenimientoCatalogoProductos1MouseClicked(evt);
            }
        });
        btnMantenimientoCatalogoProductos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMantenimientoCatalogoProductos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_edit_property_32px.png"))); // NOI18N
        btnMantenimientoCatalogoProductos1.add(lblIconoMantenimientoCatalogoProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblMantenimientoCatalogoProductos3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoCatalogoProductos3.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoCatalogoProductos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoCatalogoProductos3.setText("Inventario Bodega");
        btnMantenimientoCatalogoProductos1.add(lblMantenimientoCatalogoProductos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 20));

        lblMantenimientoCatalogoProductos4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoCatalogoProductos4.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoCatalogoProductos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoCatalogoProductos4.setText("Mantenimiento ");
        btnMantenimientoCatalogoProductos1.add(lblMantenimientoCatalogoProductos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        pnlMenu.add(btnMantenimientoCatalogoProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, 110));

        btnInventarioBodega.setBackground(new java.awt.Color(45, 83, 150));
        btnInventarioBodega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnInventarioBodega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventarioBodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventarioBodegaMouseClicked(evt);
            }
        });
        btnInventarioBodega.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoInventarioBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_view_details_32px.png"))); // NOI18N
        btnInventarioBodega.add(lblIconoInventarioBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblInventarioBodega2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInventarioBodega2.setForeground(new java.awt.Color(242, 242, 242));
        lblInventarioBodega2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventarioBodega2.setText("Bodega");
        btnInventarioBodega.add(lblInventarioBodega2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 20));

        lblInventarioBodega1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInventarioBodega1.setForeground(new java.awt.Color(242, 242, 242));
        lblInventarioBodega1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventarioBodega1.setText("Inventario");
        btnInventarioBodega.add(lblInventarioBodega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        pnlMenu.add(btnInventarioBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 150, 110));

        btnMantenimientoCatalogoBodega.setBackground(new java.awt.Color(45, 83, 150));
        btnMantenimientoCatalogoBodega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnMantenimientoCatalogoBodega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimientoCatalogoBodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantenimientoCatalogoBodegaMouseClicked(evt);
            }
        });
        btnMantenimientoCatalogoBodega.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMantenimientoCatalogoBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_warehouse_32px.png"))); // NOI18N
        btnMantenimientoCatalogoBodega.add(lblIconoMantenimientoCatalogoBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblMantenimientoCatalogoBodega2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoCatalogoBodega2.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoCatalogoBodega2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoCatalogoBodega2.setText("Catálogo Bodega");
        btnMantenimientoCatalogoBodega.add(lblMantenimientoCatalogoBodega2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 20));

        lblMantenimientoCatalogoBodega1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMantenimientoCatalogoBodega1.setForeground(new java.awt.Color(242, 242, 242));
        lblMantenimientoCatalogoBodega1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimientoCatalogoBodega1.setText("Mantenimiento ");
        btnMantenimientoCatalogoBodega.add(lblMantenimientoCatalogoBodega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        pnlMenu.add(btnMantenimientoCatalogoBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 110));

        btnRegresar.setBackground(new java.awt.Color(45, 83, 150));
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        lblIconoRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_go_back_32px.png"))); // NOI18N

        lblRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(242, 242, 242));
        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegresar.setText("Regresar");

        javax.swing.GroupLayout btnRegresarLayout = new javax.swing.GroupLayout(btnRegresar);
        btnRegresar.setLayout(btnRegresarLayout);
        btnRegresarLayout.setHorizontalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnRegresarLayout.setVerticalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenu.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 30));

        pnlBackbround.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 920, 420));

        pnlTitulo.setBackground(new java.awt.Color(0, 49, 110));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(242, 242, 242));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Inventario Hospital Odontológico");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        lblModulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblModulo.setForeground(new java.awt.Color(242, 242, 242));
        lblModulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModulo.setText("Menú Bodega");
        pnlTitulo.add(lblModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/Isotipo.HospitalOdontológico.UNICAH (4).png"))); // NOI18N
        pnlTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 90));

        pnlBackbround.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 710, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackbround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackbround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMantenimientoCatalogoBodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoCatalogoBodegaMouseClicked
        MantenimientoCatalogoBodegaView mantenimientoCatalogoBodegaView = new MantenimientoCatalogoBodegaView();
        mantenimientoCatalogoBodegaView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoCatalogoBodegaMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        MenuInicioView menuInicioView = new MenuInicioView();
        menuInicioView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnInventarioBodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioBodegaMouseClicked
        InventarioBodegaView inventarioBodegaView = new InventarioBodegaView();
        inventarioBodegaView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInventarioBodegaMouseClicked

    private void btnMantenimientoCatalogoProductos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoCatalogoProductos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientoCatalogoProductos1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBodegaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBodegaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBodegaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBodegaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBodegaView().setVisible(true);
            }
        });
    }
    
    private void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(45,83,150));
    }
    
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(0,49,110));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnInventarioBodega;
    private javax.swing.JPanel btnMantenimientoCatalogoBodega;
    private javax.swing.JPanel btnMantenimientoCatalogoProductos1;
    private javax.swing.JPanel btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIconoInventarioBodega;
    private javax.swing.JLabel lblIconoMantenimientoCatalogoBodega;
    private javax.swing.JLabel lblIconoMantenimientoCatalogoProductos1;
    private javax.swing.JLabel lblIconoRegresar;
    private javax.swing.JLabel lblIconoUsuarioAcual;
    private javax.swing.JLabel lblInventarioBodega1;
    private javax.swing.JLabel lblInventarioBodega2;
    private javax.swing.JLabel lblMantenimientoCatalogoBodega1;
    private javax.swing.JLabel lblMantenimientoCatalogoBodega2;
    private javax.swing.JLabel lblMantenimientoCatalogoProductos3;
    private javax.swing.JLabel lblMantenimientoCatalogoProductos4;
    private javax.swing.JLabel lblMensajeBienvenida;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JPanel pnlBackbround;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlUsuario;
    // End of variables declaration//GEN-END:variables
}
