/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Menus;

import Controllers.Controllers.LoginController;
import Controllers.Controllers.MenuSuministrosController;
import java.awt.Color;
import javax.swing.JPanel;
import Views.Mantenimientos.GenerarSuministrosView;
import Views.Mantenimientos.InventarioSuministroView;
import Views.Mantenimientos.MantenimientoProductosCompuestosView;

/**
 *
 * @author danie
 */
public class MenuSuministrosView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public MenuSuministrosView() {
        initComponents();
        noFocusJButtons();
        LoginController.setLabelUsrLogueado(this.lblUsuarioActual);
        MenuSuministrosController menuSuministrosController = new MenuSuministrosController();
        menuSuministrosController.AccesoModulos(this.btnMantenimientoInventarioSuministros, 
            this.btnInventarioSuministros, this.btnGenerarSuministro, this.btnMantenimientoProductosCompuestos);
    }
    
    private void noFocusJButtons()
    {
        this.btnInventarioSuministros.setFocusable(false);
        this.btnInventarioSuministros.setFocusable(false);
        this.btnGenerarSuministro.setFocusable(false);
        this.btnMantenimientoProductosCompuestos.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackbround = new javax.swing.JPanel();
        pnlUsuario = new javax.swing.JPanel();
        lblIconoUsuarioActual = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        lblMensajeBienvenida = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JPanel();
        lblIconoRegresar = new javax.swing.JLabel();
        lblRegresar = new javax.swing.JLabel();
        btnMantenimientoProductosCompuestos = new javax.swing.JButton();
        btnInventarioSuministros = new javax.swing.JButton();
        btnGenerarSuministro = new javax.swing.JButton();
        btnMantenimientoInventarioSuministros = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblModulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBackbround.setBackground(new java.awt.Color(0, 49, 110));
        pnlBackbround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUsuario.setBackground(new java.awt.Color(0, 49, 110));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUsuarioActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_user_32px.png"))); // NOI18N
        pnlUsuario.add(lblIconoUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblUsuarioActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioActual.setForeground(new java.awt.Color(242, 242, 242));
        lblUsuarioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlUsuario.add(lblUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 28));

        lblMensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensajeBienvenida.setForeground(new java.awt.Color(242, 242, 242));
        lblMensajeBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeBienvenida.setText("Bienvenido(a)");
        pnlUsuario.add(lblMensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 28));

        pnlBackbround.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        pnlMenu.setBackground(new java.awt.Color(0, 49, 110));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(45, 83, 150));
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        lblIconoRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_go_back_32px.png"))); // NOI18N

        lblRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(242, 242, 242));
        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegresar.setText("Regresar");

        javax.swing.GroupLayout btnRegresarLayout = new javax.swing.GroupLayout(btnRegresar);
        btnRegresar.setLayout(btnRegresarLayout);
        btnRegresarLayout.setHorizontalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnRegresarLayout.setVerticalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenu.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, 30));

        btnMantenimientoProductosCompuestos.setBackground(new java.awt.Color(45, 83, 150));
        btnMantenimientoProductosCompuestos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMantenimientoProductosCompuestos.setForeground(new java.awt.Color(242, 242, 242));
        btnMantenimientoProductosCompuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_product_32px.png"))); // NOI18N
        btnMantenimientoProductosCompuestos.setText("Mantenimiento Productos Compuestos");
        btnMantenimientoProductosCompuestos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMantenimientoProductosCompuestos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMantenimientoProductosCompuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoProductosCompuestosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMantenimientoProductosCompuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 180, 130));

        btnInventarioSuministros.setBackground(new java.awt.Color(45, 83, 150));
        btnInventarioSuministros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInventarioSuministros.setForeground(new java.awt.Color(242, 242, 242));
        btnInventarioSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_view_details_32px.png"))); // NOI18N
        btnInventarioSuministros.setText("Inventario Suministros");
        btnInventarioSuministros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInventarioSuministros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInventarioSuministros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioSuministrosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInventarioSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 130));

        btnGenerarSuministro.setBackground(new java.awt.Color(45, 83, 150));
        btnGenerarSuministro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarSuministro.setForeground(new java.awt.Color(242, 242, 242));
        btnGenerarSuministro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_barcode_32px.png"))); // NOI18N
        btnGenerarSuministro.setText("Generar Suministros");
        btnGenerarSuministro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarSuministro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGenerarSuministro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarSuministroActionPerformed(evt);
            }
        });
        pnlMenu.add(btnGenerarSuministro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 180, 130));

        btnMantenimientoInventarioSuministros.setBackground(new java.awt.Color(45, 83, 150));
        btnMantenimientoInventarioSuministros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMantenimientoInventarioSuministros.setForeground(new java.awt.Color(242, 242, 242));
        btnMantenimientoInventarioSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_box_32px.png"))); // NOI18N
        btnMantenimientoInventarioSuministros.setText("Mantenimiento Inventario Suministros");
        btnMantenimientoInventarioSuministros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMantenimientoInventarioSuministros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMantenimientoInventarioSuministros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoInventarioSuministrosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMantenimientoInventarioSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 180, 130));

        pnlBackbround.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 920, 420));

        pnlTitulo.setBackground(new java.awt.Color(0, 49, 110));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(242, 242, 242));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Inventario Hospital Odontológico");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        lblModulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblModulo.setForeground(new java.awt.Color(242, 242, 242));
        lblModulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModulo.setText("Menú Suministros");
        pnlTitulo.add(lblModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/Isotipo.HospitalOdontológico.UNICAH_SM.png"))); // NOI18N
        pnlTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 90));

        pnlBackbround.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 710, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackbround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackbround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        MenuInicioView menuInicioView = new MenuInicioView();
        menuInicioView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnMantenimientoProductosCompuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoProductosCompuestosActionPerformed
        MantenimientoProductosCompuestosView mantenimientoProductosCompuestosView = new MantenimientoProductosCompuestosView();
        mantenimientoProductosCompuestosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoProductosCompuestosActionPerformed

    private void btnInventarioSuministrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioSuministrosActionPerformed
        InventarioSuministroView inventarioSuministroView = new InventarioSuministroView();
        inventarioSuministroView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInventarioSuministrosActionPerformed

    private void btnGenerarSuministroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarSuministroActionPerformed
        GenerarSuministrosView generarSuministrosView = new GenerarSuministrosView();
        generarSuministrosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenerarSuministroActionPerformed

    private void btnMantenimientoInventarioSuministrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoInventarioSuministrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientoInventarioSuministrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSuministrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSuministrosView().setVisible(true);
            }
        });
    }
    
    private void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(45,83,150));
    }
    
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(0,49,110));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarSuministro;
    private javax.swing.JButton btnInventarioSuministros;
    private javax.swing.JButton btnMantenimientoInventarioSuministros;
    private javax.swing.JButton btnMantenimientoProductosCompuestos;
    private javax.swing.JPanel btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIconoRegresar;
    private javax.swing.JLabel lblIconoUsuarioActual;
    private javax.swing.JLabel lblMensajeBienvenida;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JPanel pnlBackbround;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlUsuario;
    // End of variables declaration//GEN-END:variables
}
