/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Menus;

import Controllers.Controllers.LoginController;
import Controllers.Controllers.MenuInicioController;
import java.awt.Color;
import javax.swing.JPanel;
import Views.Mantenimientos.AlertasView;
import Views.Mantenimientos.FacturacionView;
import Views.Mantenimientos.InformacionPersonalView;
import Views.Mantenimientos.MantenimientoProveedoresView;
import Views.Mantenimientos.MantenimientoUsuariosView;
import Views.Mantenimientos.MantenimientoComprasView;

/**
 *
 * @author danie
 */
public class MenuInicioView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public MenuInicioView() 
    {
        initComponents();
        LoginController.setLabelUsrLogueado(this.lblUsuarioActual);
        MenuInicioController menuIncioController = new MenuInicioController();
        menuIncioController.AccesoModulos(this.btnVentas, this.btnSuministros, 
                this.btnProveedores, this.btnCompras, this.btnBodega,
                this.btnUsuarios, this.btnAlertas);
        noFocusJButtons();
    }
    
    private void noFocusJButtons()
    {
        this.btnVentas.setFocusable(false);
        this.btnSuministros.setFocusable(false);
        this.btnProveedores.setFocusable(false);
        this.btnCompras.setFocusable(false);
        this.btnBodega.setFocusable(false);
        this.btnUsuarios.setFocusable(false);
        this.btnAlertas.setFocusable(false);
        this.btnInformacionPersonal.setFocusable(false);
        this.btnCerrarSesion.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackbround = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnBodega = new javax.swing.JButton();
        btnSuministros = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnInformacionPersonal = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnAlertas = new javax.swing.JButton();
        pnlUsuario = new javax.swing.JPanel();
        lblIconoUsuarioActual = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        lblMensajeBienvenida = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblModulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBackbround.setBackground(new java.awt.Color(0, 49, 110));
        pnlBackbround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(0, 49, 110));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setBackground(new java.awt.Color(45, 83, 150));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(242, 242, 242));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_exit_32px.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 180, 100));

        btnVentas.setBackground(new java.awt.Color(45, 83, 150));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(242, 242, 242));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_sales_performance_32px_1.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 180, 100));

        btnBodega.setBackground(new java.awt.Color(45, 83, 150));
        btnBodega.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBodega.setForeground(new java.awt.Color(242, 242, 242));
        btnBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_warehouse_32px.png"))); // NOI18N
        btnBodega.setText("Bodega");
        btnBodega.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBodega.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBodegaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, 100));

        btnSuministros.setBackground(new java.awt.Color(45, 83, 150));
        btnSuministros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuministros.setForeground(new java.awt.Color(242, 242, 242));
        btnSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_medical_bag_32px_3.png"))); // NOI18N
        btnSuministros.setText("Suministros");
        btnSuministros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuministros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSuministros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuministrosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 180, 100));

        btnUsuarios.setBackground(new java.awt.Color(45, 83, 150));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(242, 242, 242));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_user_groups_32px.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, 100));

        btnCompras.setBackground(new java.awt.Color(45, 83, 150));
        btnCompras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(242, 242, 242));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_purchase_order_32px.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 180, 100));

        btnInformacionPersonal.setBackground(new java.awt.Color(45, 83, 150));
        btnInformacionPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInformacionPersonal.setForeground(new java.awt.Color(242, 242, 242));
        btnInformacionPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_user_32px.png"))); // NOI18N
        btnInformacionPersonal.setText("Información Personal");
        btnInformacionPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInformacionPersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInformacionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionPersonalActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInformacionPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 180, 100));

        btnProveedores.setBackground(new java.awt.Color(45, 83, 150));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(242, 242, 242));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_supplier_32px.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        pnlMenu.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 180, 100));

        btnAlertas.setBackground(new java.awt.Color(45, 83, 150));
        btnAlertas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlertas.setForeground(new java.awt.Color(242, 242, 242));
        btnAlertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_box_important_32px.png"))); // NOI18N
        btnAlertas.setText("Alertas");
        btnAlertas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlertas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlertasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 180, 100));

        pnlBackbround.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 920, 420));

        pnlUsuario.setBackground(new java.awt.Color(0, 49, 110));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUsuarioActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_user_32px.png"))); // NOI18N
        pnlUsuario.add(lblIconoUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        lblUsuarioActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioActual.setForeground(new java.awt.Color(242, 242, 242));
        lblUsuarioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlUsuario.add(lblUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 28));

        lblMensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensajeBienvenida.setForeground(new java.awt.Color(242, 242, 242));
        lblMensajeBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeBienvenida.setText("Bienvenido(a)");
        pnlUsuario.add(lblMensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 28));

        pnlBackbround.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        pnlTitulo.setBackground(new java.awt.Color(0, 49, 110));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(242, 242, 242));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Inventario Hospital Odontológico");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        lblModulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblModulo.setForeground(new java.awt.Color(242, 242, 242));
        lblModulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModulo.setText("Menú Inicio");
        pnlTitulo.add(lblModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/Isotipo.HospitalOdontológico.UNICAH_SM.png"))); // NOI18N
        pnlTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 90));

        pnlBackbround.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 720, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackbround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackbround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        LoginController.Logout();
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        FacturacionView facturacionView = new FacturacionView();
        facturacionView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBodegaActionPerformed
        MenuBodegaView menuBodegaView = new MenuBodegaView();
        menuBodegaView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBodegaActionPerformed

    private void btnInformacionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionPersonalActionPerformed
        InformacionPersonalView informacionPersonalView = new InformacionPersonalView();
        informacionPersonalView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInformacionPersonalActionPerformed

    private void btnSuministrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuministrosActionPerformed
        MenuSuministrosView menuSuministrosView  = new MenuSuministrosView();
        menuSuministrosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuministrosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        MantenimientoUsuariosView mantenimientoUsuariosView = new MantenimientoUsuariosView();
        mantenimientoUsuariosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        MantenimientoComprasView registrarCompraView = new MantenimientoComprasView();
        registrarCompraView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        MenuProveedoresView menuProveedoresView = new MenuProveedoresView();
        menuProveedoresView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnAlertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertasActionPerformed
        AlertasView alertasView = new AlertasView();
        alertasView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlertasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicioView().setVisible(true);
            }
        });
    }
    
    private void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(45,83,150));
    }
    
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(0,49,110));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlertas;
    private javax.swing.JButton btnBodega;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnInformacionPersonal;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnSuministros;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIconoUsuarioActual;
    private javax.swing.JLabel lblMensajeBienvenida;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JPanel pnlBackbround;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlUsuario;
    // End of variables declaration//GEN-END:variables
}
