/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Mantenimientos;

import Controllers.Controllers.UsuarioController;
import Utils.Cache.UsuariosCache;
import Views.Menus.MenuInicioView;
import java.awt.Color;
import javax.swing.JPanel;
import Views.TablasGrande.TablaGrandeUsuariosView;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;

/**
 *
 * @author danie
 */
public class MantenimientoUsuariosView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    
    Integer Id_usuario; 
    private DefaultListModel modeloLstPrivilegiosSeleccionados = new DefaultListModel();
    private DefaultListModel modeloLstPrivilegiosDisponibles = new DefaultListModel(); 
    private JFrame getFrame()
    {
        return this;
    }

    public MantenimientoUsuariosView() 
    {
        initComponents();
        this.tableUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.lstPrivilegiosSeleccionados.setModel(modeloLstPrivilegiosSeleccionados);
        this.lstPrivilegiosDisponibles.setModel(modeloLstPrivilegiosDisponibles);
        UsuarioController.LlenarTableUsuarios(this.tableUsuarios);
        UsuarioController.LlenarCmbAreas(this.cmbArea);
        UsuarioController.LlenarListPrivilegios(this.modeloLstPrivilegiosDisponibles);
        UsuarioController.FiltroTableUsuarios(tableUsuarios, txtBuscar);
    }
    
    private void LimpiarInputs()
    {
        this.txtIdentidad.setText(null);
        this.txtNombre.setText(null);
        this.txtApellido.setText(null);
        this.txtApellido.setText(null);
        this.txtCorreo.setText(null);
        this.txtUsuario.setText(null);
        this.txtContrasenia.setText(null);
        this.cmbArea.setSelectedIndex(0);
        this.cmbEstado.setSelectedIndex(0);
    }
    
    private void LimpiarErrLabels()
    {
        this.lblErrorIdentidad.setText(null);
        this.lblErrorNombre.setText(null);
        this.lblErrorApellido.setText(null);
        this.lblErrorCorreo.setText(null);
        this.lblErrorUsuario.setText(null);
        this.lblErrorContrasenia.setText(null);
        this.lblErrorArea.setText(null);
        this.lblErrorEstado.setText(null);
        this.lblErrorPrivilegios.setText(null);
    }
    
    private void ResetJlists()
    {
        this.modeloLstPrivilegiosSeleccionados.clear();
        this.modeloLstPrivilegiosDisponibles.clear();
        UsuarioController.LlenarListPrivilegios(modeloLstPrivilegiosDisponibles);
    }
    
    private void LlenarDatos()
    {
        UsuariosCache usuarioCache = new UsuariosCache();
        if(usuarioCache.isDatosCompartidos())
        {
            this.btnAgregar.setEnabled(false);
            this.btnEditar.setEnabled(true);
            cmbEstado.setEnabled(true);
            
            this.Id_usuario = usuarioCache.getUsuario().getUsrId();
            this.txtIdentidad.setText(usuarioCache.getUsuario().getUsrIdentidad());
            this.txtNombre.setText(usuarioCache.getUsuario().getUsrNombre());
            this.txtApellido.setText(usuarioCache.getUsuario().getUsrApellido());
            this.txtCorreo.setText(usuarioCache.getUsuario().getUsrCorreo());
            this.txtUsuario.setText(usuarioCache.getUsuario().getUsrUsuario());
            this.cmbEstado.setSelectedItem(usuarioCache.getUsuario().getUsrEstado());
            this.cmbArea.setSelectedItem(usuarioCache.getUsuario().getAreDescripcion());
            UsuarioController.LlenarListPrivilegios(this.modeloLstPrivilegiosDisponibles);
            UsuarioController.LlenarListPrivilegiosUsuario(this.modeloLstPrivilegiosSeleccionados, this.modeloLstPrivilegiosDisponibles, this.Id_usuario);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackbround = new javax.swing.JPanel();
        pnlUsuario = new javax.swing.JPanel();
        lblIconoUsuarioActual = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        lblMensajeBienvenida = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JPanel();
        lblIconoRegresar = new javax.swing.JLabel();
        lblRegresar = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblErrorCorreo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        lblContrasenia = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblPrivilegios = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrivilegiosDisponibles = new javax.swing.JList<>();
        btnQuitarPrivilegios = new javax.swing.JButton();
        btnAgregarPrivilegios = new javax.swing.JButton();
        lblPrivilegios1 = new javax.swing.JLabel();
        lblPrivilegios2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPrivilegiosSeleccionados = new javax.swing.JList<>();
        lblIdentidad = new javax.swing.JLabel();
        lblErrorEstado = new javax.swing.JLabel();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorIdentidad = new javax.swing.JLabel();
        lblErrorUsuario = new javax.swing.JLabel();
        lblErrorPrivilegios = new javax.swing.JLabel();
        lblErrorContrasenia = new javax.swing.JLabel();
        lblErrorApellido = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        cmbArea = new javax.swing.JComboBox<>();
        lblErrorArea = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnVisualizarTabla = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblModulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBackbround.setBackground(new java.awt.Color(0, 49, 110));
        pnlBackbround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUsuario.setBackground(new java.awt.Color(0, 49, 110));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUsuarioActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_user_32px.png"))); // NOI18N
        pnlUsuario.add(lblIconoUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        lblUsuarioActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioActual.setForeground(new java.awt.Color(242, 242, 242));
        lblUsuarioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioActual.setText("Dra. Lourdes");
        pnlUsuario.add(lblUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 28));

        lblMensajeBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensajeBienvenida.setForeground(new java.awt.Color(242, 242, 242));
        lblMensajeBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeBienvenida.setText("Bienvenido(a)");
        pnlUsuario.add(lblMensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 28));

        pnlBackbround.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        pnlMenu.setBackground(new java.awt.Color(0, 49, 110));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(45, 83, 150));
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 196)));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        lblIconoRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/icons8_go_back_32px.png"))); // NOI18N

        lblRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(242, 242, 242));
        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegresar.setText("Regresar");

        javax.swing.GroupLayout btnRegresarLayout = new javax.swing.GroupLayout(btnRegresar);
        btnRegresar.setLayout(btnRegresarLayout);
        btnRegresarLayout.setHorizontalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnRegresarLayout.setVerticalGroup(
            btnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMenu.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 30));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(242, 242, 242));
        lblCorreo.setText("Correo: ");
        pnlMenu.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        pnlMenu.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 210, -1));

        lblErrorCorreo.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorCorreo.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 210, 20));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlMenu.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 210, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlMenu.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 210, -1));

        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(242, 242, 242));
        lblApellido.setText("Apellido: ");
        pnlMenu.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        pnlMenu.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(242, 242, 242));
        lblNombre.setText("Nombre:");
        pnlMenu.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(242, 242, 242));
        lblUsuario.setText("Usuario: ");
        pnlMenu.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id usuario", "Identidad", "Nombre", "Apellido", "Correo electrónico", "Nombre de usuario", "Estado", "Id Área", "Descripción Área"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuarios.setMinimumSize(new java.awt.Dimension(130, 0));
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tableUsuarios);

        pnlMenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 1260, 140));

        lblContrasenia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(242, 242, 242));
        lblContrasenia.setText("Contraseña: ");
        pnlMenu.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbEstado.setEnabled(false);
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        pnlMenu.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 130, -1));

        lblPrivilegios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrivilegios.setForeground(new java.awt.Color(242, 242, 242));
        lblPrivilegios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrivilegios.setText("Seleccionados");
        pnlMenu.add(lblPrivilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, -1, -1));

        txtIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentidadActionPerformed(evt);
            }
        });
        pnlMenu.add(txtIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 210, -1));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(242, 242, 242));
        lblEstado.setText("Estado: ");
        pnlMenu.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));
        pnlMenu.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 210, -1));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(242, 242, 242));
        lblBuscar.setText("Buscar: ");
        pnlMenu.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        pnlMenu.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 590, -1));

        lstPrivilegiosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPrivilegiosDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstPrivilegiosDisponibles);

        pnlMenu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 220, 170));

        btnQuitarPrivilegios.setText("Quitar");
        btnQuitarPrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarPrivilegiosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnQuitarPrivilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 70, -1));

        btnAgregarPrivilegios.setText("Agregar");
        btnAgregarPrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPrivilegiosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAgregarPrivilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, -1, -1));

        lblPrivilegios1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrivilegios1.setForeground(new java.awt.Color(242, 242, 242));
        lblPrivilegios1.setText("Privilegios:");
        pnlMenu.add(lblPrivilegios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        lblPrivilegios2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrivilegios2.setForeground(new java.awt.Color(242, 242, 242));
        lblPrivilegios2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrivilegios2.setText("Disponibles");
        pnlMenu.add(lblPrivilegios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 90, -1));

        jScrollPane4.setViewportView(lstPrivilegiosSeleccionados);

        pnlMenu.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 220, 170));

        lblIdentidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIdentidad.setForeground(new java.awt.Color(242, 242, 242));
        lblIdentidad.setText("Identidad: ");
        pnlMenu.add(lblIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblErrorEstado.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorEstado.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 160, 20));

        lblErrorNombre.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorNombre.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, 20));

        lblErrorIdentidad.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorIdentidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorIdentidad.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 20));

        lblErrorUsuario.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorUsuario.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 210, 20));

        lblErrorPrivilegios.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorPrivilegios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorPrivilegios.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorPrivilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, 240, 20));

        lblErrorContrasenia.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorContrasenia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorContrasenia.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 210, 20));

        lblErrorApellido.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorApellido.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 210, 20));

        lblArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArea.setForeground(new java.awt.Color(242, 242, 242));
        lblArea.setText("Área:");
        pnlMenu.add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaActionPerformed(evt);
            }
        });
        pnlMenu.add(cmbArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 130, -1));

        lblErrorArea.setBackground(new java.awt.Color(255, 51, 51));
        lblErrorArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorArea.setForeground(new java.awt.Color(231, 0, 2));
        pnlMenu.add(lblErrorArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 160, 20));

        btnCancelar.setBackground(new java.awt.Color(59, 103, 181));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(242, 242, 242));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 90, -1));

        btnVisualizarTabla.setBackground(new java.awt.Color(59, 103, 181));
        btnVisualizarTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVisualizarTabla.setForeground(new java.awt.Color(242, 242, 242));
        btnVisualizarTabla.setText("Visualizar Tabla");
        btnVisualizarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarTablaMouseClicked(evt);
            }
        });
        btnVisualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarTablaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnVisualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 340, 140, -1));

        btnEditar.setBackground(new java.awt.Color(59, 103, 181));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(242, 242, 242));
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlMenu.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 90, -1));

        btnAgregar.setBackground(new java.awt.Color(59, 103, 181));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(242, 242, 242));
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 90, -1));

        pnlBackbround.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1310, 530));

        pnlTitulo.setBackground(new java.awt.Color(0, 49, 110));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(242, 242, 242));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Inventario Hospital Odontológico");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        lblModulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblModulo.setForeground(new java.awt.Color(242, 242, 242));
        lblModulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModulo.setText("Mantenimiento Usuarios");
        pnlTitulo.add(lblModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/Isotipo.HospitalOdontológico.UNICAH (4).png"))); // NOI18N
        pnlTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 80, 90));

        pnlBackbround.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1010, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackbround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackbround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        MenuInicioView homeView = new MenuInicioView();
        homeView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentidadActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAreaActionPerformed

    private void btnVisualizarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarTablaMouseClicked
        
    }//GEN-LAST:event_btnVisualizarTablaMouseClicked

    private void tableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseClicked
        int seleccion = this.tableUsuarios.rowAtPoint(evt.getPoint()); 
        
        this.btnAgregar.setEnabled(false);
        this.btnEditar.setEnabled(true);
        cmbEstado.setEnabled(true);
        
        this.Id_usuario = Integer.parseInt((String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion, 0)))); 
        this.txtIdentidad.setText(String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion, 1)));
        this.txtNombre.setText(String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion, 2)));
        this.txtApellido.setText(String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion, 3)));
        this.txtCorreo.setText(String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion, 4)));
        this.txtUsuario.setText(String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion, 5)));
        this.cmbEstado.setSelectedItem(String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion,6)));
        this.cmbArea.setSelectedItem(String.valueOf(this.tableUsuarios.getModel().getValueAt(seleccion,8)));
        UsuarioController.LlenarListPrivilegios(this.modeloLstPrivilegiosDisponibles);
        UsuarioController.LlenarListPrivilegiosUsuario(this.modeloLstPrivilegiosSeleccionados, this.modeloLstPrivilegiosDisponibles, this.Id_usuario);
    }//GEN-LAST:event_tableUsuariosMouseClicked

    private void btnVisualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarTablaActionPerformed

        TablaGrandeUsuariosView tablaGrandeUsuariosView = new TablaGrandeUsuariosView()
        {
            @Override
            public void dispose()
            {
                LlenarDatos();
                getFrame().setVisible(true);
                super.dispose();
            }
        };
        
        tablaGrandeUsuariosView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVisualizarTablaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.btnVisualizarTabla.setEnabled(true);
        this.btnAgregar.setEnabled(true);
        this.btnEditar.setEnabled(false);
        this.cmbEstado.setEnabled(false);
        this.tableUsuarios.clearSelection();
        this.btnVisualizarTabla.setEnabled(true); 
        this.ResetJlists();
        this.LimpiarInputs();
        this.LimpiarErrLabels();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(!UsuarioController.MantenimientoUsuarios("editar", this.Id_usuario, 
            this.txtIdentidad.getText(), this.txtNombre.getText(), 
            this.txtApellido.getText(), this.txtCorreo.getText(), 
            this.txtUsuario.getText(), this.txtContrasenia.getText(), 
            this.cmbEstado.getSelectedItem().toString(), this.cmbArea.getSelectedIndex(),
            this.lblErrorIdentidad, this.lblErrorNombre, this.lblErrorApellido, 
            this.lblErrorCorreo, this.lblErrorUsuario, this.lblErrorContrasenia, 
            this.lblErrorEstado, this.lblErrorPrivilegios, this.modeloLstPrivilegiosSeleccionados))
        {
            this.btnAgregar.setEnabled(true);
            this.btnEditar.setEnabled(false);
            this.cmbEstado.setEnabled(false);
            this.LimpiarInputs();
            this.ResetJlists();
            UsuarioController.LlenarTableUsuarios(tableUsuarios);
        }    
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tableUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableUsuariosMouseEntered

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(!UsuarioController.MantenimientoUsuarios("insertar", 0, 
            this.txtIdentidad.getText(), this.txtNombre.getText(), 
            this.txtApellido.getText(), this.txtCorreo.getText(), 
            this.txtUsuario.getText(), this.txtContrasenia.getText(), 
            "Activo", this.cmbArea.getSelectedIndex(),
            this.lblErrorIdentidad, this.lblErrorNombre, this.lblErrorApellido, 
            this.lblErrorCorreo, this.lblErrorUsuario, this.lblErrorContrasenia, 
            this.lblErrorEstado, this.lblErrorPrivilegios, this.modeloLstPrivilegiosSeleccionados))
        {
            this.LimpiarInputs();
            this.ResetJlists();
            UsuarioController.LlenarTableUsuarios(tableUsuarios);
        }    
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarPrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPrivilegiosActionPerformed
        UsuarioController.AgregarListPrivilegiosSeleccionados(this.modeloLstPrivilegiosSeleccionados, this.lstPrivilegiosDisponibles, this.modeloLstPrivilegiosDisponibles);
    }//GEN-LAST:event_btnAgregarPrivilegiosActionPerformed

    private void btnQuitarPrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarPrivilegiosActionPerformed
        UsuarioController.QuitarListPrivilegiosSeleccionados(this.modeloLstPrivilegiosSeleccionados, this.lstPrivilegiosSeleccionados, this.modeloLstPrivilegiosDisponibles);
    }//GEN-LAST:event_btnQuitarPrivilegiosActionPerformed

    private void lstPrivilegiosDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPrivilegiosDisponiblesMouseClicked
    
    }//GEN-LAST:event_lstPrivilegiosDisponiblesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoUsuariosView().setVisible(true);
            }
        });
    }
    
    private void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(45,83,150));
    }
    
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(0,49,110));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarPrivilegios;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnQuitarPrivilegios;
    private javax.swing.JPanel btnRegresar;
    private javax.swing.JButton btnVisualizarTabla;
    private javax.swing.JComboBox<String> cmbArea;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblErrorApellido;
    private javax.swing.JLabel lblErrorArea;
    private javax.swing.JLabel lblErrorContrasenia;
    private javax.swing.JLabel lblErrorCorreo;
    private javax.swing.JLabel lblErrorEstado;
    private javax.swing.JLabel lblErrorIdentidad;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorPrivilegios;
    private javax.swing.JLabel lblErrorUsuario;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIconoRegresar;
    private javax.swing.JLabel lblIconoUsuarioActual;
    private javax.swing.JLabel lblIdentidad;
    private javax.swing.JLabel lblMensajeBienvenida;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrivilegios;
    private javax.swing.JLabel lblPrivilegios1;
    private javax.swing.JLabel lblPrivilegios2;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JList<String> lstPrivilegiosDisponibles;
    private javax.swing.JList<String> lstPrivilegiosSeleccionados;
    private javax.swing.JPanel pnlBackbround;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
